services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Kachhapa-network

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin port
    networks:
      - Kachhapa-network

  flask:
    build:
      context: .
      dockerfile: Flask/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - myapp_socket:/tmp
    ports:
      - "5001:5000"
    networks:
      - Kachhapa-network

  webapp:
    build: ./webapp
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - myapp_socket:/tmp
    networks:
      - Kachhapa-network

volumes:
  postgres_data:
  myapp_socket:

networks:
  Kachhapa-network: