version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Kachhapa-network

  flask:
    build: ./Flask
    depends_on:
      - postgres
    volumes:
      - myapp_socket:/tmp
    ports:
      - "5001:5000"
    networks:
      - Kachhapa-network

  webapp:
    build: ./webapp
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - myapp_socket:/tmp
    networks:
      - Kachhapa-network

volumes:
  postgres_data:
  myapp_socket:

networks:
  Kachhapa-network: