"""Added Avatar columns

Revision ID: 2ac04c2d4414
Revises: 84c8accb089d
Create Date: 2026-04-09 14:16:11.026728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac04c2d4414'
down_revision = '84c8accb089d'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'character',
        sa.Column(
            'avatar_mode',
            sa.String(length=20),
            nullable=False,
            server_default='initials'
        )
    )

    op.add_column(
        'character',
        sa.Column('avatar_color', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'character',
        sa.Column('avatar_text_color', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'character',
        sa.Column('avatar_image_url', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'character',
        sa.Column('avatar_thumb_url', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'character',
        sa.Column('avatar_preset_key', sa.String(length=100), nullable=True)
    )
    op.add_column(
        'character',
        sa.Column(
            'avatar_shape',
            sa.String(length=20),
            nullable=False,
            server_default='circle'
        )
    )
    op.add_column(
        'character',
        sa.Column('avatar_frame_color', sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('avatar_frame_color')
        batch_op.drop_column('avatar_shape')
        batch_op.drop_column('avatar_preset_key')
        batch_op.drop_column('avatar_thumb_url')
        batch_op.drop_column('avatar_image_url')
        batch_op.drop_column('avatar_text_color')
        batch_op.drop_column('avatar_color')
        batch_op.drop_column('avatar_mode')

    # ### end Alembic commands ###
