"""added column for CalendarEvent player visibility

Revision ID: 688150376679
Revises: 6e323b5b25d8
Create Date: 2026-04-05 16:49:05.218140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688150376679'
down_revision = '6e323b5b25d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_player_visible', sa.Boolean(), nullable=False))

    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_month_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('journal_minute', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'calendar', ['calendar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('journal_minute')
        batch_op.drop_column('journal_hour')
        batch_op.drop_column('journal_day')
        batch_op.drop_column('journal_month_index')
        batch_op.drop_column('journal_year')
        batch_op.drop_column('calendar_id')

    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_column('is_player_visible')

    # ### end Alembic commands ###
