"""updates to Calendar table

Revision ID: 6e323b5b25d8
Revises: 8a64fa353e5b
Create Date: 2026-04-04 22:02:03.116197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e323b5b25d8'
down_revision = '8a64fa353e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_column('time_scale')
        batch_op.drop_column('hours_in_day')
        batch_op.drop_column('day_start_time')
        batch_op.drop_column('minutes_in_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes_in_hour', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hours_in_day', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_scale', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
